/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: maxpanysh (https://sketchfab.com/maxpanysh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/silent-ash-bc44272e8c1047148b33c913e659fcfa
Title: Silent Ash
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { events, useFrame, useThree } from "@react-three/fiber";
import { a } from '@react-spring/three'
import RabbitScene from '../assets/3d/silent_ash.glb'

const Rabbit = ({ IsRotating, setIsRotating, ...props }) => {
    const RabbitRef = useRef()
    const { gl, viewport } = useThree()
    const lastX = useRef(0)
    const rotationSpeed = useRef(0)
    const dampigFactor = 0.95
    const handlPointerDown = (e) => {
        e.stopProgation()
        e.preventDefault()
        setIsRotating(true)
        const clientX = e.touches ? e.touches[0].clientX : e.clientX
        lastX.current = clientX
    }
    const handlPointerUp = (e) => {
        e.stopProgation()
        e.preventDefault()
        setIsRotating(false)
        const clientX = e.touches ? e.touches[0].clientX : e.clientX
        const delta = (clientX - lastX.current) / viewport.width
        RabbitRef.current.rotation.y += delta * 0.001 * Math.PI
    }
    const handlPointerMove = (e) => {
        e.stopProgation()
        e.preventDefault()

    }

    const { nodes, materials } = useGLTF(RabbitScene);
    return (
        <a.group ref={RabbitRef} {...props} >
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.398}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0.002, 2.616, 0.003]}>
                        <mesh
                            geometry={nodes.Object_4.geometry}
                            material={materials.Bunny}
                        />
                        <mesh
                            geometry={nodes.Object_5.geometry}
                            material={materials.Skateboard}
                        />
                    </group>
                </group>
            </group>
        </a.group>
    );
}


export default Rabbit